name: bedwars
version: '${version}'
main: mc.bedwars.BedWars
api-version: '1.20'
commands:
  reset:
    usage: /<command>
    description: "重置游戏"
  start:
    usage: /<command>
    description: "开始游戏"